site_name: Meteor tutorial tools
theme: readthedocs
pages:
- Overview: index.md
- Guide for making a new tutorial: new-tutorial.md
- Guide for updating a tutorial: update-tutorial.md
- Importing a git repo: tutorial-step-diff-compiler.md
- Displaying code diffs: tutorial-diff-box.md
- Specifying metadata and steps: tutorial-registry.md
- Building a tutorial viewer app: tutorial-viewer.md